# Usa la imagen base de OpenJDK 21
FROM amazoncorretto:21

# Crea un directorio de trabajo
WORKDIR /app

# Copia el archivo JAR generado en la carpeta target
COPY target/ApiCrudUniquindio2025_Quarkus-1.0.0-SNAPSHOT-runner.jar app.jar

# Expone el puerto en el que corre Quarkus
EXPOSE 9090

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]


